name: Trigger Jobs

on:
  pull_request_target:
    types: [synchronize, labeled, reopened]

jobs:
  Trigger-Admit-Test:
    runs-on: ubuntu-latest
    steps:  
      - name: List reviews on the pull request
        shell: bash
        run: |
          token=${{ secrets.GITHUB_TOKEN }}
          response=$(curl --request GET \
            --url https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \
            --header 'Authorization: $base64AuthInfo' \
            --header 'Content-Type: application/json')

          echo $response | jq '.[] | select(.state=="APPROVED")'
      
      - name: PR comment
        if: contains(github.event.pull_request.labels.*.name, 'Approved')
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            run starrocks_admit_test
          GITHUB_TOKEN: ${{ secrets.PAT }}
