name: automerge
on:
  pull_request_target:
    types:
      - labeled
jobs:
  automerge:
    runs-on: ubuntu-latest
    
    steps:
      - name: enable automerge
        if: contains( github.event.pull_request.labels.*.name, 'automerge')
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.PAT }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: rebase
          
      - uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            '## Cherry-pick Checklist:'
            - [ ] cherry-picked to branch-2.5
            - [ ] cherry-picked to branch-2.4
            - [ ] cherry-picked to branch-2.3
            - [ ] cherry-picked to branch-2.2
          GITHUB_TOKEN: ${{ secrets.PAT  }}
          reactions: eyes
#   remover:
#     runs-on: ubuntu-latest
#     if: contains( github.event.pull_request.labels.*.name, 'be-build')
#     steps:
#       - run: sleep 5
 
#       - uses: actions-ecosystem/action-remove-labels@v1
#         with:
#           labels: |
#             be-build
