name: checkbox
on:
  pull_request_target:
    types: [edited, opened, reopened]
    
jobs:
  checkmate:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub event
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event.body) }}
        run: echo "$GITHUB_CONTEXT"
          
#     - uses: actions/checkout@v3
    
#     - uses: kentaro-m/task-completed-checker-action@v0.1.0
#       with:
#         repo-token: "${{ secrets.GITHUB_TOKEN }}"
          
#     - name: Validate Checklists
#       if: >
#         startsWith(github.event.pull_request.title, '[BugFix]') && 
#         !contains(github.event.pull_request.title, 'cherry-pick') && 
#         !contains(github.event.pull_request.title, 'backport')
#       uses: roryq/checkmate@master
