name: checkbox
on:
  pull_request_target:
    types: [edited, opened, reopened]
    
jobs:
  checkmate:
    runs-on: ubuntu-latest
    steps:
#       - name: Dump GitHub event
#         env:
#           GITHUB_CONTEXT: ${{ toJson(github.event.pull_request.body) }}
#         run:
      - name: get issue number
        if: contains(toJson(github.event.pull_request.body), 'Fixes #')
        id: issue
        run: |
            echo '${{ toJson(github.event.pull_request.body) }}' | grep 'Fixes #' | cut -d ' ' -f 2 

#       - name: echo result
#         if: steps.issue.outputs.result != ''
#         run: echo ${{ steps.issue.outputs.result }}

      - name: feature
#         if: contains(toJson(github.event.pull_request.body), '[x] Feature')
        env:
          GITHUB_CONTEXT1: ${{ toJson(github.event.changes.body) }}
          GITHUB_CONTEXT2: ${{ toJson(github.event.pull_request.body) }}
        run: |
          echo ${{ toJson(github.event.pull_request.body) }}
#echo "$GITHUB_CONTEXT1"
#          echo "$GITHUB_CONTEXT2"
          
      - name: add branch-2.5 label
        if: >
          contains(toJson(github.event.pull_request.body), '[x] 2.5') &&
          contains(toJson(github.event.changes.body), '[ ] 2.5')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            2.5
      - name: add branch-2.4 label
        if: >
          contains(toJson(github.event.pull_request.body), '[x] 2.4') &&
          contains(toJson(github.event.changes.body), '[ ] 2.4')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            2.4
            
      - name: check-done
        if: >
          contains(toJson(github.event.pull_request.body), '[ ] I have checked the version labels which the pr will be auto backported to target branch')
        run: |
          echo "You must mark this checkbox - I have checked the version labels which the pr will be auto backported to target branch"
          exit 1
          
        #   if [[ "\r\n- [x] Feature\r\n" == *"[x] Feature"* ]]; then    echo "ok"; fi
        #echo "$GITHUB_CONTEXT"
          
#     - uses: actions/checkout@v3
    
#     - uses: kentaro-m/task-completed-checker-action@v0.1.0
#       with:
#         repo-token: "${{ secrets.GITHUB_TOKEN }}"
          
#     - name: Validate Checklists
#       if: >
#         startsWith(github.event.pull_request.title, '[BugFix]') && 
#         !contains(github.event.pull_request.title, 'cherry-pick') && 
#         !contains(github.event.pull_request.title, 'backport')
#       uses: roryq/checkmate@master
