name: comment

on:
  issue_comment:
    types: 
      - created
      - edited

jobs:
  check-done:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }} && contains(github.event.head_commit.message, 'I like pizza')
    steps:
#       - name: Github API Request
#         id: request
#         uses: octokit/request-action@v2.0.0
#         with:
#           route: ${{ github.event.issue.pull_request.url }}
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       - name: Checkout PR Branch
#         uses: actions/checkout@v2
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           repository: ${{ fromJson(steps.request.outputs.data).head.repo.full_name }}
#           ref: ${{ steps.pr_data.outputs.branch }}
      - run: echo "hello"
      - name: find comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          body-includes: "check done"
          direction: first

      - name: echo info
        if: steps.fc.outputs.comment-id != 0
        run: |
          echo "You must finish check done"
          exit 1
