name: comment

on:
  pull_request_target:
    types:
      - edited
  issue_comment:
    types: 
      - created
      - edited

jobs:
  check-done:
    runs-on: ubuntu-latest
#    if: ${{ github.event.issue.pull_request }}
    steps:
#       - name: Github API Request
#         id: request
#         uses: octokit/request-action@v2.0.0
#         with:
#           route: ${{ github.event.issue.pull_request.url }}
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       - name: Checkout PR Branch
#         uses: actions/checkout@v2
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           repository: ${{ fromJson(steps.request.outputs.data).head.repo.full_name }}
#           ref: ${{ steps.pr_data.outputs.branch }}
#       - run: echo "hello"
#       - uses: actions/checkout@v3
      
      - name: find comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          body-includes: "- [x] check done"


      - name: find comment
        uses: peter-evans/find-comment@v2
        id: fcbp
        with:
          issue-number: ${{ github.event.number }}
          body-includes: "- [x] check done"
          
          
      - name: echo info
        run: |
          echo ${{ steps.fcbp.outputs.comment-id }}
          echo ${{ steps.fcbp.outputs.comment-body }}
          echo ${{ steps.fcbp.outputs.comment-author }}
