name: checkbox
on:
  pull_request_target:
    types: [edited, opened, reopened]
    
jobs:
  checkmate:
    runs-on: ubuntu-latest
    steps:
#       - name: Dump GitHub event
#         env:
#           GITHUB_CONTEXT: ${{ toJson(github.event.pull_request.body) }}
#         run:

      - name: feature
#         if: contains(toJson(github.event.pull_request.body), '[x] Feature')
        env:
          GITHUB_CONTEXT1: ${{ toJson(github.event.changes.body) }}
          GITHUB_CONTEXT2: ${{ toJson(github.event.pull_request.body) }}
        run: |
          echo "$GITHUB_CONTEXT1"
          echo "$GITHUB_CONTEXT2"
          
      - name: check-done
        if: >
          contains(toJson(github.event.pull_request.body), '[ ] I have checked the version labels which the pr will be auto backported to target branch')
        run: |
          echo "You must mark this checkbox - I have checked the version labels which the pr will be auto backported to target branch"
          exit 1
          
        #   if [[ "\r\n- [x] Feature\r\n" == *"[x] Feature"* ]]; then    echo "ok"; fi
        #echo "$GITHUB_CONTEXT"
          
#     - uses: actions/checkout@v3
    
#     - uses: kentaro-m/task-completed-checker-action@v0.1.0
#       with:
#         repo-token: "${{ secrets.GITHUB_TOKEN }}"
          
#     - name: Validate Checklists
#       if: >
#         startsWith(github.event.pull_request.title, '[BugFix]') && 
#         !contains(github.event.pull_request.title, 'cherry-pick') && 
#         !contains(github.event.pull_request.title, 'backport')
#       uses: roryq/checkmate@master
