on:
  pull_request:
    types: [edited, opened, reopened]
    
name: Checklist Check
jobs:
  checkmate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Validate Checklists
      uses: roryq/checkmate@master
