name: clang-tidy-review
on: [pull_request]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - run: sh build.sh --clean --be
#     - name: get build
#       run: |
#         rm -rf be/src
#         time scp jenkins@ci01:~/userContent/be-build-12072.tar.gz .
#         tar xzf be-build-12072.tar.gz
#         workdir=$(pwd)
#         echo $workdir
        
    - uses: ZedThree/clang-tidy-review@v0.10.0
      id: review
      with:
        # List of packages to install
        # apt_packages: liblapack-dev
        # CMake command to run in order to generate compile_commands.json
        # cmake_command: cmake . -DCMAKE_EXPORT_COMPILE_COMMANDS=on
        build_dir: be/build_Release
        base_dir: be
