name: clang-tidy-review
on: [pull_request]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    
#    - run: sh build.sh --clean --be

    - name: get build
      run: |
        time scp jenkins@ci01:~/userContent/be-build-12072.tar.gz .
        mkdir temp
        tar xzf be-build-12072.tar.gz -C temp
        cp -r temp/be/build_Release be/
        workdir=$(pwd)
        echo $workdir
        
        scl enable llvm-toolset-7 'clang -v'
        scl enable llvm-toolset-7 'lldb -v'
        scl enable llvm-toolset-7 bash
        
    - uses: ZedThree/clang-tidy-review@v0.10.0
      id: review
      with:
        # List of packages to install
        # apt_packages: liblapack-dev
        # CMake command to run in order to generate compile_commands.json
        # cmake_command: cmake . -DCMAKE_EXPORT_COMPILE_COMMANDS=on
        build_dir: be/build_Release
