name: clang-tidy-review
on: [pull_request]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    
#    - run: sh build.sh --clean --be

    - name: get build
      run: |
        time scp jenkins@ci01:~/userContent/be-build-12072.tar.gz .
        mkdir temp
        tar xzf be-build-12072.tar.gz -C temp
        cp -r temp/be/build_Release be/
        workdir=$(pwd)
        echo $workdir
        
        scl enable llvm-toolset-7 'clang -v'
        scl enable llvm-toolset-7 'lldb -v'
        scl enable llvm-toolset-7 bash
        cp ~/clang-tidy-diff.py .
        
    - name: Create results directory
      run: |
        mkdir clang-tidy-result
    - name: Analyze
      run: |
        git diff -U0 HEAD^ | python clang-tidy-diff.py -p1 -path be/build_Release -export-fixes clang-tidy-result/fixes.yml
        
    - name: Run clang-tidy-pr-comments action
      uses: platisd/clang-tidy-pr-comments@master
      with:
        # The GitHub token (or a personal access token)
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # The path to the clang-tidy fixes generated previously
        clang_tidy_fixes: clang-tidy-result/fixes.yml
        # Optionally set to true if you want the Action to request
        # changes in case warnings are found
        request_changes: true
        # Optionally set the number of comments per review
        # to avoid GitHub API timeouts for heavily loaded
        # pull requests
        suggestions_per_comment: 10
        
#     - uses: ZedThree/clang-tidy-review@v0.10.1
#       id: review
#       with:
#         # List of packages to install
#         # apt_packages: liblapack-dev
#         # CMake command to run in order to generate compile_commands.json
#         # cmake_command: cmake . -DCMAKE_EXPORT_COMPILE_COMMANDS=on
#         build_dir: be/build_Release
