name: markdownlint

on: 
  pull_request:
    paths:
      - 'docs/**'

jobs:
  delivery:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

#       # Example 1
#     - name: Get changed files
#       id: changed-files
#       uses: tj-actions/changed-files@v34
#     - name: git diff
#       id: diff
#       run : echo "files=$(git diff HEAD HEAD^  --name-only -- '*.md')" >> $GITHUB_OUTPUT
      
# echo "files=$(git diff --name-only | grep -E '(.md$)')" >> $GITHUB_OUTPUT
#     - name: List all changed files
#       run: |
#         for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
#           echo "$file was changed"
#         done
          
#     - name: Run mdl
#       uses: actionshub/markdownlint@2.0.2
#       with:
#         path: docs

    - name: markdownlint-cli
      uses: nosborn/github-action-markdown-cli@v3.2.0
      with:
        files: docs # ${{ steps.diff.outputs.files }}
        
#     - uses: articulate/actions-markdownlint@v1.1.0
#       with:
#         config: ".github/markdown-lint.json"
#         files: 'docs/**/*.md'
#         ignore: node_modules
#         version: 0.28.1
