name: title-check

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - unlabeled

jobs:
  pr-title-check:
    runs-on: ubuntu-latest
    steps:
      - uses: thehanimo/pr-title-checker@v1.3.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false
          configuration_path: ".github/pr-title-checker-config.json"
          
      - name : Print Title of PR
        run: |
          echo The Title of your PR is ${{ github.event.pull_request.title }}

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: 13
          body-includes: What type of PR is this
          
      - run: |
         echo ${{ steps.fc.outputs.comment-id }}
         echo ${{ steps.fc.outputs.comment-body }}
         echo ${{ steps.fc.outputs.comment-author }}
