name: BE Build
on:
  push:
    branches:
      - main
      - 'branch*'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'be/**.cpp'
      - 'be/**.hpp'
      - 'be/**.h'
  check_run:
    types: [completed]
jobs:
  build:
    name: BE Sonar Build
    #if: github.event.pull_request.paths && startsWith(github.event.pull_request.paths, 'be/src')
    runs-on: self-hosted
    env:
      PR_NUMBER: ${{ github.event.number  }}
      PR_PATH: ${{ github.event.pull_request.paths }}
    steps:
      - run: |
          echo $PR_PATH
          
      - name: set up
        run: |
          sudo rm -rf ../starrocks/*
          time scp jenkins@ci01:~/userContent/be-build-$PR_NUMBER.tar.gz .
          tar xzf be-build-$PR_NUMBER.tar.gz
          workdir=$(pwd)
          echo $workdir
          sed -i "s|\/root\/starrocks|$workdir|g" be/build-wrapper/build-wrapper-dump.json

      - name: Run sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: 391d6539e2d09aed3d187353bfd85fefa7a4c281
        run: |
          sonar-scanner -Dsonar.organization=starrocks -Dsonar.projectKey=Starrocks_starrocks -Dsonar.cfamily.build-wrapper-output="be/build-wrapper" -Dsonar.host.url="https://sonarcloud.io" -Dsonar.sources="be/src" -Dsonar.pullrequest.key=${{ github.event.number }} -Dsonar.pullrequest.base=${{ github.base_ref }} -Dsonar.pullrequest.branch=${{ github.head_ref }}
